language: node_js
node_js:
    - 10.16
script:
    - npm run styleguide:build
deploy:
    provider: pages
    local_dir: styleguide
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    name: Mike Barkmin
    on:
        branch: master
